group: constainer
language: node_js
cache:
  directories:
    - node_modules

stages:
  - test
  - name: deploy
    if: type = push AND branch = main

jobs:
  include:
    - stage: test
      script: npm run test
      env:
        - JOB_NAME=tests
    - script: npm run lint
      env:
        - JOB_NAME=linters
    - stage: deploy
      script: npm run deploy
      env:
        - JOB_NAME=deploy
